# Site settings
title: The Blockchain club at California State University, Fullerton
lab_name: Blockchain Club
author: >
  Wenlin Han
institution: California State University, Fullerton
email: whan@fullerton.edu
description: >
  The Blockchain club at California State University, Fullerton
baseurl: ""
url: "https://tuffytoken.github.io/"
twitter_username: 
github_username:  tuffytoken
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
