# Site settings
title: A multi-disciplinary Web 3.0 research lab at California State University, Fullerton
lab_name: TuffyVerse Lab
author: >
  Wenlin Han
institution: California State University, Fullerton
email: whan@fullerton.edu
description: >
  A multi-disciplinary Web 3.0 research lab at California State University, Fullerton
baseurl: ""
url: "https://tuffyverselab.github.io"
twitter_username: 
github_username:  
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
